<a href="https://colab.research.google.com/github/sushanttwayana/NLP_ML-DL/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [6]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [10]:
### Vocabulary size
voc_size=10000

**One Hot Encoding**

In [11]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[1757, 1459, 8311, 833], [1757, 1459, 8311, 6509], [1757, 4509, 8311, 2057], [8955, 8861, 8046, 656, 1876], [8955, 8861, 8046, 656, 2090], [2870, 1757, 2113, 8311, 7452], [4704, 4397, 9986, 656]]


**Word Embedding Represntation**

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1757 1459 8311  833]
 [   0    0    0    0 1757 1459 8311 6509]
 [   0    0    0    0 1757 4509 8311 2057]
 [   0    0    0 8955 8861 8046  656 1876]
 [   0    0    0 8955 8861 8046  656 2090]
 [   0    0    0 2870 1757 2113 8311 7452]
 [   0    0    0    0 4704 4397 9986  656]]


In [15]:
## post padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1757 1459 8311  833    0    0    0    0]
 [1757 1459 8311 6509    0    0    0    0]
 [1757 4509 8311 2057    0    0    0    0]
 [8955 8861 8046  656 1876    0    0    0]
 [8955 8861 8046  656 2090    0    0    0]
 [2870 1757 2113 8311 7452    0    0    0]
 [4704 4397 9986  656    0    0    0    0]]


In [16]:
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
embedded_docs[0]

array([1757, 1459, 8311,  833,    0,    0,    0,    0], dtype=int32)

In [21]:
# each will be represented by 10 dimns
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 123ms/step


array([[-1.0297261e-02, -4.5989372e-02,  2.3293439e-02,  1.1976063e-02,
        -8.9909062e-03,  1.3850961e-02, -4.5274448e-02, -2.3423756e-02,
         2.0029496e-02, -2.5338484e-02],
       [ 1.4989320e-02, -2.6969004e-02,  8.5598007e-03,  2.3963835e-02,
        -4.2482115e-02,  2.5623653e-02,  1.7428908e-02, -1.6864847e-02,
        -7.5293705e-04,  7.0660114e-03],
       [-8.2028620e-03,  4.0138911e-02, -2.4268115e-02,  9.0072863e-03,
        -5.4977648e-03, -2.4221445e-02, -4.6745427e-03, -4.1649211e-02,
         2.4284992e-02, -3.6814727e-02],
       [-8.5661523e-03, -2.8664947e-02,  6.3754618e-05,  3.0869547e-02,
        -1.0045957e-02, -2.7651941e-02, -3.5020649e-02, -3.8365711e-02,
         3.7222851e-02,  4.7601607e-02],
       [ 3.4210395e-02, -1.7822497e-03,  2.4515871e-02, -2.6117075e-02,
        -4.0849686e-02, -1.5448581e-02, -2.9007709e-02,  3.4580939e-03,
        -3.8459204e-02,  4.4991683e-02],
       [ 3.4210395e-02, -1.7822497e-03,  2.4515871e-02, -2.6117075e-02,
   

In [24]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 63ms/step
[[[-1.02972612e-02 -4.59893718e-02  2.32934393e-02  1.19760633e-02
   -8.99090618e-03  1.38509609e-02 -4.52744476e-02 -2.34237555e-02
    2.00294964e-02 -2.53384840e-02]
  [ 1.49893202e-02 -2.69690044e-02  8.55980068e-03  2.39638351e-02
   -4.24821153e-02  2.56236531e-02  1.74289085e-02 -1.68648474e-02
   -7.52937049e-04  7.06601143e-03]
  [-8.20286199e-03  4.01389115e-02 -2.42681149e-02  9.00728628e-03
   -5.49776480e-03 -2.42214445e-02 -4.67454270e-03 -4.16492112e-02
    2.42849924e-02 -3.68147269e-02]
  [-8.56615230e-03 -2.86649466e-02  6.37546182e-05  3.08695473e-02
   -1.00459568e-02 -2.76519414e-02 -3.50206494e-02 -3.83657105e-02
    3.72228511e-02  4.76016067e-02]
  [ 3.42103951e-02 -1.78224966e-03  2.45158710e-02 -2.61170752e-02
   -4.08496857e-02 -1.54485814e-02 -2.90077087e-02  3.45809385e-03
   -3.84592041e-02  4.49916832e-02]
  [ 3.42103951e-02 -1.78224966e-03  2.45158710e-02 -2.61170752e-02
   -4.08496857e-02 -1.54485814e